pool:
  vmImage: windows-latest

steps:

- checkout: self
  clean: true
  persistCredentials: true

- task: CredScan@3
  inputs: 
    outputFormat: 'csv'

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'

- task: VulnerabilityAssessment@0

- task: PublishSecurityAnalysisLogs@2

- task: PostAnalysis@1
  inputs:
    CredScan: true
    Semmle: true
