pool:
  vmImage: windows-latest

steps:

- checkout: self
  clean: true
  persistCredentials: true

- task: Semmle@1
  inputs:
    sourceCodeDirectory: '$(Build.SourcesDirectory)/views'
    language: 'javascript'
    querySuite: 'Recommended'
    timeout: '1800'
    ram: '16384'
    addProjectDirToScanningExclusionList: true

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'

- task: VulnerabilityAssessment@0

- task: PublishSecurityAnalysisLogs@2

- task: PostAnalysis@1
  inputs:
    BinSkim: true
    CredScan: true
    Semmle: true

- download: current
  patterns: '**/*.json'

- download: current
  patterns: '**/*.xml'
